### ISSUE TITLE
Module name conflict between erlang_localtime (erlware_commons) and qdate_localtime

### ISSUE THREAD

**Issue by jhw** [choptastic/qdate#26] opened 2016-09-23 16:22 UTC
Hi,

I noticed you have a new qdate_localtime package, taken from erlang_localtime. Not sure if this is a bug or a feature but erlware_commons is used in a lot of places; if you now use qdate with it (within a release) it will generate a module naming conflict - I had to use a qdate commit which predates the creation of qdate_localtime. 

Maybe use erlang_localtime as a dependency, or do some module renaming ?

Just my 2c

Thx!

**Comment by choptastic** [comment] 2016-09-23 17:07
Hi!

The usage of qdate_localtime is intentional, as I didn't feel like trying to get my changes merged into the mainline erlang_localtime repo every time. It always felt like pulling teeth trying to get something merged in, so I just gave up and forked. I used qdate_localtime as a name to avoid the naming conflict with erlang_localtime (specifically with hex, that way if you want erlang_localtime, you get mainline, and if you want qdate_localtime, you get the fork redesigned to work with qdate).

*That said*, I don't see how there's a naming conflict at all with erlware_commons.  erlware_commons does not specify erlang_localtime as a dependency, and has no modules itself that conflict with qdate or qdate_localtime.  I suspect you simply have a latent copy of erlang_localtime laying about in your dependencies that is generating the conflict.

Which module, in particular, is generating the conflict?

**Comment by jhw** [comment] 2016-09-23 19:03
I don't know at this stage. I have a medium sized Erlang.mk project which
specifies neither erlware_commons or erlang_localtime in the makefile. But
even if I clean deps, both those projects end up in deps upon make. So one
of the other deps is pulling them in somewhere. I will let u know if I find
anything

**Comment by choptastic** [comment] 2016-09-23 19:11
Weird. I'm curious to know what is causing the conflict. Please let me know when you find out.

**Comment by jhw** [comment] 2016-09-23 19:21
Found it. One of my own submodules had an explicit erlang_localtime dep. Removed it and everything works fine. Sorry for trouble. And thanks for qdate - I use it all the time. Best wishes + closed

**Closed** 2016-09-23 19:21 UTC

**Comment by choptastic** [comment] 2016-09-23 19:27
Awesome! Glad you were able to find the cause, and thank you for the kind words! I'm glad you find it useful!
